### ISSUE TITLE
蓄電池の状態をget、setする際にフィードバックされるデータの見方が分かりません

### ISSUE THREAD

**Issue by hayasheesh** [takuroumi/der_tester#15]
# 概要
der_testerを動かし、set_and_get.pyを書き換え、リモートで蓄電池の状態をget,setすることに成功したのですが、帰ってくるデータが以下のようになり、
**｛set_property_value (acChargeUpperLimit=6) ...ng (06)
get_property_value (acChargeableElectricEnergy) ...ok (0)｝**
(06)や（0）の単位が分からず、実験が進まない状態になっております。
https://echonet.jp/web_api_guideline/　
にて仕様を調べようとしたのですが、どこを調べば良いのかわからず、躓いてしまいました。
もし良い資料があれば、ぜひ共有して頂きたいです。
# 再現手順
１環境構築を完了し、蓄電池とコンピュータを繋げる。
２set_and_get.pyのget内容、set内容を"acChargeableElectricEnergy"などの指示に書き換える。
３実行する。
# その他
初めてのissue利用ですので、情報不足や無礼をお許しください。補足説明が必要な場合は随時対応します。よろしくお願いいたします。

**Comment by iot-ex** [comment]
iot-exサポートチームです。弊社よりメール等でサポートいたしましょうか？

**Comment by takuroumi** [comment]
@hayasheesh さま
起票ありがとうございます。情報不足で申し訳ございません。

カッコ内の表記には IoT-HUB API における response value が入ります。
GETの場合は Command Value に対応する数値等の情報（acChargeableElectricEnergy であれば W の値）が入ります。

SETの場合の response value の詳細につきましては @iot-ex さまに伺っていただけますと幸いです。

https://github.com/takuroumi/der_tester/blob/33037f9026e5de18e572edebe2076b235dfca8fc/tools/scripts/iothub/set_and_get.py#L83-L84

**Comment by hayasheesh** [comment]
@takuroumi 様
詳細な説明ありがとうございます。引き続きよろしくお願いいたします。

**Comment by MasakiImanaka** [comment]
@hayasheesh さま
ツールをお使いいただき、誠にありがとうございます。
私の理解では、ECHONET Driverが対応するIoT-HUB APIは基本的にECHONET Liteの仕様に準拠しています。
バージョンによる差異は多少あるかもしれませんが、基本は下記ホームページの「API仕様部」と「機器仕様部」のPDFに仕様があります。
https://echonet.jp/web_api_guideline/

例えば、下記の機器仕様部
https://echonet.jp/wp/wp-content/uploads/pdf/General/Standard/web_api/ECHONET_Lite_Web_API_Dev_Specs_v1.5.0.pdf
で、「acChargeUpperLimit」を検索すると２か所ヒットし、
２か所目は239ページにあります。
下にスクロールすると、240ページの1行目に
"unit": "%",
とあり、単位がパーセントだということが分かります。

その他、ご不明な点がありましたら、遠慮なくご返信下さい。

**Comment by hayasheesh** [comment]
@MasakiImanaka 
返信ありがとうございます。仕様の調べ方を確認できました。
また疑問点があれば連絡致します。引き続きよろしくお願いいたします。

**Comment by Honekawasujiemon** [comment]
私も参加しました。馬場博幸。

**Comment by hayasheesh** [comment]
> iot-exサポートチームです。弊社よりメール等でサポートいたしましょうか？

返信遅くなり申し訳ありません。SETの場合の response value の詳細はどのように調べればいいのでしょうか？

**Comment by iot-ex** [comment]
response_code に応じた response_value 値が応答します。
SETの場合、SETとしたプロパティに対して、実際に送信した値（＝ECHONET Liteの edt値）が設定させています。
他は、response_code 自体に相当する値となっており、例えば、esvであれば、ECHONET Liteの esv 値が設定されています。

**Comment by hayasheesh** [comment]
issueは解決されました。
第２部　echonet lite 通信ミドルウェア仕様　の３－５，３－１０　を読むことで解決されました。
 @takuroumi @iot-ex @Honekawasujiemon @MasakiImanaka 
皆さんありがとうございました。
