### ISSUE TITLE
HEMSコントローラーから運転モードの変更ができない

### ISSUE THREAD

**Issue by daisukekodaira** [takuroumi/der_tester#17]
# 問題点
研究のため、オムロン社の蓄電池をHEMSコントローラ(IoT-HUB)より操作できる状態にしたいが、運転モード(epc=0xda)に、スタンバイ(edt=0x44)や、充電(edt=0x42)を送信しても、応答結果がNGが返却され、運転モードの切替ができない。
運転モードの変更にあたり、遠隔操作設定(epc=0x93)や、設定値で必要な AC 充電量設定値(epc=0xAA)および、AC 放電量設定値(epc=0xAB)については、適宜、正しいと思われる値を設定の上、動作確認を実施したが、運転モードの変更ができない。

# 製品の仕様
1. 蓄電システム用ゲートウェイ（KP-GWBT-A）
2. パワーコンディショナー（KPAC-B25）
3. 蓄電池ユニット（KP-BU42-A）

#  知りたいこと
御社製品をHEMSコントローラより運転モードを実施するためには、どのような手順もしくは機器側の設定が必要か？

# ステータス
オムロン社へ問い合わせ中

**Comment by takuroumi** [comment]
ご相談誠にありがとうございます。

> HEMSコントローラ

こちらは IoT-HUB のことでしょうか？あるいは Nature Remo E のことでしょうか？
可能な範囲で、実行したコードおよびエラーログをコメントにて共有いただくことは可能でしょうか？
何卒よろしくお願いいたします。

**Comment by daisukekodaira** [comment]
@takuroumi コメントありがとうございます。

> こちらは IoT-HUB のことでしょうか？あるいは Nature Remo E のことでしょうか？  

IoT-HUBのことです。

> 可能な範囲で、実行したコードおよびエラーログをコメントにて共有いただくことは可能でしょうか？


実際におこなったコマンド等の資料を添付します（オムロン社の担当者に説明するための資料です）
[OMRON様向け問合せ資料.pptx](https://github.com/takuroumi/der_tester/files/15315392/OMRON.pptx)

**Comment by takuroumi** [comment]
ご返信ありがとうございます。
対象の蓄電池について、特定のプロパティのSETができない（NGが返される）こと承知いたしました。

当方にあまり知見がなく恐縮ですが、以下を確認いただけると原因の切り分けができるかと思料しました。

必須プロパティにおいて、SET可能なプロパティはございますか？
（運転モード、AC充電量設定値、に限らず、writableな項目全てSETができない状況かどうかの確認になるかと存じます）

**Comment by daisukekodaira** [comment]
@takuroumi 
試行錯誤の末にHEMSコントローラーから充電動作を行えることを確認しました。原因としては、メーカーの独自の運転モード（経済モード、安心モード等）により、特定の時間はHEMSコマンドを受け付けないという蓄電池(またはPCS)内部の設定がありました。その時間帯はある程度設定が可能です。コマンドを受け付けない時間帯を避けることで、充電のコマンドがHEMSコントローラー(今回はIoT-HUB)から通り、実際に充電動作をすることを確認しました。
ご対応頂きまして、ありがとうございました。
